export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'

export const GET_PROFILE_DESCRIPTION_REQUEST = 'GET_PROFILE_DESCRIPTION_REQUEST'
export const GET_PROFILE_DESCRIPTION_SUCCESS = 'GET_PROFILE_DESCRIPTION_SUCCESS'
export const GET_PROFILE_DESCRIPTION_FAIL = 'GET_PROFILE_DESCRIPTION_FAIL'

export const GET_PROFILE_PROJECT_REQUEST = 'GET_PROFILE_PROJECT_REQUEST'
export const GET_PROFILE_PROJECT_SUCCESS = 'GET_PROFILE_PROJECT_SUCCESS'
export const GET_PROFILE_PROJECT_FAIL = 'GET_PROFILE_PROJECT_FAIL'

export const GET_PROFILE_SKILLPROF_REQUEST = 'GET_PROFILE_SKILLPROF_REQUEST'
export const GET_PROFILE_SKILLPROF_SUCCESS = 'GET_PROFILE_SKILLPROF_SUCCESS'
export const GET_PROFILE_SKILLPROF_FAIL = 'GET_PROFILE_SKILLPROF_FAIL'

export const GET_PROFILE_SKILLS_REQUEST = 'GET_PROFILE_SKILLS_REQUEST'
export const GET_PROFILE_SKILLS_SUCCESS = 'GET_PROFILE_SKILLS_SUCCESS'
export const GET_PROFILE_SKILLS_FAIL = 'GET_PROFILE_SKILLS_FAIL'
